* Jupyterling

For Python teachers and students that find Jupyter too confusing.

Jupyerling is a [Pyodide](https://pyodide.org/en/stable/) app entirely hosted in your browser.

Always one notebook, consisting of 1..N code cells.

Each cell supports Python code.

If the cell is evaluated, it also has a results box right below it.

If the results are stale, the results box is greyed out.

There is always only 1 cell currently selected. It has a yellow box around it to indicate which one.

** Interaction

Normal keyboard input edits Python code in the current cell.

Ctrl + Up:     move selection one cell up
Ctrl + Down:   move selection one cell down
Ctrl + Enter:  run current cell
Ctrl + Delete: remove current cell
Shift + Enter: run the current cell, select below

** Evaluator State Display

The key principle is that the current evaluator state is always reflected in the UI.

The indicator is a little snake icon.

If we currently computed the state up to cell N, the snake icon is sitting alongside cell N.

If we are currently computing up to cell N, the snake is slithering alongside cell N.

** Evaluator Implementation

Evaluator uses ~eval()~ and ~exec()~ built-ins.

Evaluator tracks interpreter states corresponding to evaluating up to K cells. The states are tracked as ~globals~ and
~locals~ to pass to ~eval()~ and ~exec()~.

If ~K < N~ for ~N~ cells displayed in the UI, the ~K+1..N~ cells are considered stale.

When a request comes in to evaluate an updated code at cell ~I~, the evaluator keeps the prefix states ~0 .. I-1~,
starts recomputing the ~I~ state based off ~I-1~ state and the updated code, and invalidates the suffix states indexed
~I+1 .. K~.

** Two kinds of code fragments

Expressions like ~1+2~ are interpreted with ~eval~ and their results displayed.

Fragments like ~import math; print(path.sin(2))~ are interpreted with ~exec~ and their print output, if any, displayed.
